### ISSUE TITLE
Unable to launch modpacks

### ISSUE THREAD

**Issue by aDragon** [HearthProject/OneClient#7]
I am able to download packs and login but nothing happens after that. I also tried with a Vanilla 1.12.1 Minecraft instance. I am Running Archlinux.

[crash-2017-08-25_13.39.34-client.txt](https://github.com/HearthProject/OneClient/files/1249869/crash-2017-08-25_13.39.34-client.txt)

[crash-2017-08-25_13.51.35-client.txt](https://github.com/HearthProject/OneClient/files/1249871/crash-2017-08-25_13.51.35-client.txt)

[crash-2017-08-25_13.39.34-client.txt](https://github.com/HearthProject/OneClient/files/1249873/crash-2017-08-25_13.39.34-client.txt)

**Comment by NillerMedDild** [comment]
This also happens on Windows10, although I don't get crashlogs, as nothing ever launches.

**Comment by modmuss50** [comment]
@NillerMedDild is there anything the log window?

**Comment by NillerMedDild** [comment]
Ah yes, my bad. It did crash.

[Log](https://gist.github.com/NillerMedDild/59919c95c7fb25da4e7998fa270b8bdd)

**Comment by modmuss50** [comment]
What mod pack did you try?

**Comment by NillerMedDild** [comment]
Project Ozone 2, Minecraft 1.7.10

**Comment by NillerMedDild** [comment]
Age of Engineering is also unable to start, here's the [log](https://gist.github.com/NillerMedDild/3077b86c26519af3206201d90c26b6ec).

Should you prefer I moved this to a seperate issue from this, as I pretty much hijacked this one?

**Comment by modmuss50** [comment]
I fixed project ozone 2, going to push an update in about 10 mins, not sure if it will fix the other issues here or not.

**Comment by NillerMedDild** [comment]
I'm still unable to launch Project Ozone 2, [log](https://gist.github.com/NillerMedDild/89dde51a73a53dc09f74549142486c00)

**Comment by modmuss50** [comment]
Ok, so thats the same log as AOE, but different from the last one. Thats a bit of progress I guess.

**Comment by modmuss50** [comment]
Ok, tracked down the issue, its going to be a bit of work to fix so it will have to wait till im back. But going to leave the details here so I dont forget.: 

Minecraft main class looks for a `userProperties `and `profileProperties ` json file that we are not providing. It seems to be left over from when minecraft had built in twitch support so we just need to provide a dummy one (I dont see a reason to support the twitch thing)

**Comment by modmuss50** [comment]
Ok, released another build with some changes, hopefully this fixes your issue, if it doesn't I have another idea.

**Comment by aDragon** [comment]
Project Ozone 2, and FTB Infinity Evolved 1.7 seem to be launching fine, but I am unable to launch other packs including Vanilla 1.12.2, 1.9.4, COTT 1.2, and Sky Factory 3. I am running OC 0.0.2.101

[COTT crash-2017-08-29_11.42.02-client.txt](https://github.com/HearthProject/OneClient/files/1260892/crash-2017-08-29_11.42.02-client.txt)

[Skyfactory crash-2017-08-29_11.39.12-client.txt](https://github.com/HearthProject/OneClient/files/1260895/crash-2017-08-29_11.39.12-client.txt)

[Vanilla 1.9.4 crash-2017-08-29_11.45.06-client.txt](https://github.com/HearthProject/OneClient/files/1260896/crash-2017-08-29_11.45.06-client.txt)

[Vanilla 1.12.1 crash-2017-08-29_11.43.12-client.txt](https://github.com/HearthProject/OneClient/files/1260899/crash-2017-08-29_11.43.12-client.txt)
